FROM nodered/node-red:latest

RUN set -x \
    && npm install \
        node-red-contrib-alasql@latest \
        node-red-contrib-aedes@latest \
        node-red-contrib-loop@latest \
        node-red-node-mysql@latest \
        node-red-contrib-prib-functions@latest \
        node-red-contrib-influxdb@latest

COPY ./profile.d /etc/profile.d
