services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ../php:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "48080:80"
    volumes:
      - ../php:/var/www/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  nodered:
    build:
      context: .
      dockerfile: Dockerfile.rednode
    ports:
      - "41880:1880"
    volumes:
      - ../nodered:/data
    restart: unless-stopped
